# Crowdin configuration file
# see: https://support.crowdin.com/configuration-file/
#
# you will need the Java CLI client
# see: https://support.crowdin.com/cli-tool/

project_identifier: qownnotes
base_path: "."

# the api key has to be provided by ~/.crowdin.yaml
#api_key: XXXX

files:
  -
    # source files filter
    source: '/app/_locales/*/messages.json'
    # where translations live
    translation: '/app/_locales/%locale_with_underscore%/messages.json'
